version: '3.1'

services:
  postgres:
    image: 'postgres:16.1'
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./user-service/src/main/resources/init-schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
    driver: local
