version: '3.1'

services:

  user-service:
    build: .
    env_file:
      - .env
    ports:
      - '8080:8080'

  postgres:
    image: 'postgres:16.1'
    container_name: postgres-user-account
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/init-schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
    driver: local
