server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/E6L1PS/delivery-api-config.git
          search-paths:
            - '{application}/{profile}'
logging:
  level:
    org.springframework.cloud.config: DEBUG
